### ISSUE TITLE
1.4.0 fails to open: Namespace Handy not available

### ISSUE THREAD

**Issue by mkhl** [flathub/org.gnome.Lollypop#104]
The Lollypop flatpak fails to open after #103 

<details>
<summary>Output of: flatpak run org.gnome.Lollypop</summary>
<pre>
Traceback (most recent call last):
  File "/app/bin/lollypop", line 45, in <module>
    from lollypop.application import Application
  File "/app/lib/python3.7/site-packages/lollypop/application.py", line 18, in <module>
    gi.require_version("Handy", "1")
  File "/usr/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Handy not available
</pre>
</details>

This was also [reported upstream](https://gitlab.gnome.org/World/lollypop/-/issues/2556).

I believe the issue is that this upstream version depends on libhandy1 which I think is part of Gnome 3.38 but the flatpak uses the 3.36 runtime.

**Comment by BrainBlasted** [comment]
Libhandy isn't included in 3.38; You still need to bundle it.

**Comment by Eonfge** [comment]
On it. This was a big oversight on my end. Due to #101, I accidentally tested against the wrong version. In case that I can't resolve the issue in due time, I'll roll it back.

**Comment by Eonfge** [comment]
Should be resolved with #105. My apologies.
