### ISSUE TITLE
Phone integration not supported

### ISSUE THREAD

**Issue by Eonfge** [flathub/org.gnome.Lollypop#109]
When using Lollypop 1.4.1, I see that there are some features who don't seem to work. These include:
- Synchronizing albums or playlists to devices
- Converting to mp3 or AAC before synchronizing (They're unselectable)
- Converting to ogg or Flac before synchronizing (/tmp/ file access error)

### Further logging
```
[WARNING] 2020-10-13 17:52:50 SyncMenu::__add_sync_action(): 'OnePlus 7 Pro' is not in list
[ERROR] 2020-10-13 17:52:55 MtpSyncDb::load(): g-io-error-quark: File doesn’t exist (1)
[WARNING] 2020-10-13 17:53:03 DeviceWidget::__get_device_index(): 'OnePlus 7 Pro' is not in list
[WARNING] 2020-10-13 17:53:08 DeviceWidget::__get_device_index(): 'OnePlus 7 Pro' is not in list
[WARNING] 2020-10-13 17:53:11 DeviceWidget::__get_device_index(): 'OnePlus 7 Pro' is not in list
[ERROR] 2020-10-13 17:53:26 MtpSyncDb::__save(): g-io-error-quark: Error when getting information for file “/tmp/.GG4AS0”: No such file or directory (1)
[ERROR] 2020-10-13 17:53:26 MtpSyncDb::__save(): g-io-error-quark: Error when getting information for file “/tmp/.DKQAS0”: No such file or directory (1)
[WARNING] 2020-10-13 17:53:28 DeviceWidget::__get_device_index(): 'OnePlus 7 Pro' is not in list
```

**Comment by bellegarde-c** [comment]
@bilelmoussaoui /tmp looks not writable in flatpak, any way to fix this issue?

**Comment by bellegarde-c** [comment]
It's fixed in current master.

**Comment by Eonfge** [comment]
Wait, just like that? I thought it was a Flatpak related thing and I didn't want to bother you with it. Had I known this, I would have reported it a few months ago :open_mouth:

**Comment by bellegarde-c** [comment]
No, it was an issue with flatpak but I workaround it... There is a bug report opened on Flatpak page (setting TMPDIR)

**Comment by bilelmoussaoui** [comment]
> @bilelmoussaoui /tmp looks not writable in flatpak, any way to fix this issue?

By using /var/tmp or whatever api python has for getting the temporary directory. That should work fine iirc

**Comment by fin-ger** [comment]
mp3 and AAC conversion for synchronization is still grayed out for me. Is this a regression or am I missing something?

**Comment by Eonfge** [comment]
Do you have the ffmpeg additions?

> flatpak install flathub org.freedesktop.Platform.ffmpeg-full//21.08

mp3 conversion might be affected by it. If that's not it, please open another issue to keep this problem tracked

**Comment by lunaryorn** [comment]
@bellegarde-c This issue still exists for me, in version 1.4.36 🤔 

I've found https://gitlab.gnome.org/World/lollypop/-/issues/2892 upstream, but it doesn't contain any fix either 🤔 

I've seen this issue before with `/tmp`; couldn't lollypop check whether `/.flatpak-info` exists and then manually override `TMPDIR` to `$XDG_RUNTIME_DIR/app/$FLATPAK_ID`?  I could contribute a patch if this is a viable solution.
