### ISSUE TITLE
libgi too old on Debian stretch

### ISSUE THREAD

**Issue by temrix** [flathub/org.gnome.Lollypop#11]
The current flatpak version of Lollypop 0.9.604 does not transmit listening data to listenbrainz or others.

I did this in the Python3 interpreter, since Lollypop does the same:
```python3
import gi
gi.require_version('Secret', '1')
```

It does not work for me on Debian stretch with Lollypop installed from the ppa. Flatpak uses its own Python interpreter and libs but I guess it is the same issue.

See [https://gitlab.gnome.org/World/lollypop/issues/1516](https://gitlab.gnome.org/World/lollypop/issues/1516) for reference.

**Comment by TingPing** [comment]
Your issue doesn't make sense at all. What is the actual error you are getting, what is failing?

**Comment by temrix** [comment]
Lollypop does not transmit listening data to listenbrainz or librefm and logging in to librefm does not work. It seems to be a problem with Glib.

Here is the output from `$ flatpak run org.gnome.Lollypop --debug`:
```
(lollypop:3): dbind-WARNING **: 17:51:37.681: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

(lollypop:3): Gtk-WARNING **: 17:51:38.094: gtk_widget_size_allocate(): attempt to allocate widget with width -79 and height 36

(lollypop:3): Gtk-WARNING **: 17:51:38.109: Creating a portal monitor failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Keine derartige Methode »CreateMonitor«

(lollypop:3): GLib-GIO-WARNING **: 17:51:38.115: Failed to get the 'connectivity' property

(lollypop:3): GLib-GIO-WARNING **: 17:51:38.115: Failed to get the 'metered' property

(lollypop:3): GLib-GIO-WARNING **: 17:51:38.115: Failed to get the 'available' property
[DEBUG] 2018-10-14 17:51:53 PasswordsHelper::get(): Waiting Secret service
[DEBUG] 2018-10-14 17:51:53 PasswordsHelper::get(): Waiting Secret service
[DEBUG] 2018-10-14 17:52:02 PasswordsHelper::clear(): Waiting Secret service
```

**Comment by TingPing** [comment]
Sounds like `xdg-desktop-portal` on your host is too old. You may also be missing `gnome-keyring`, not sure.

**Comment by temrix** [comment]
I have no easy way to upgrade `xdg-desktop-portal` without messing up my system. `gnome-keyring` is installed though.

**Comment by temrix** [comment]
I still get the same debug messages but it now _does_ transmit to listenbrainz and librefm although I don’t remember that I changed anything. Strange but it works again.
