### ISSUE TITLE
Update to 0.9.905

### ISSUE THREAD

**Issue by alessandrococco** [flathub/org.gnome.Lollypop#15]
Hello!

Lollypop has been updated to [version 0.9.905](https://gitlab.gnome.org/World/lollypop/commit/af3cdc7085e51add7bf089f03f06880990e26b3d)

Could you update the flatpack version also? Thank you :-)

ps: I just noticed that the last flatpack version is 0.9.900, I believed it was still 0.9.612, my fault.

**Comment by bilelmoussaoui** [comment]
Done :+1:
