### ISSUE TITLE
Missing dependency: kid3-cli

### ISSUE THREAD

**Issue by da2x** [flathub/org.gnome.Lollypop#26]

**Comment by bilelmoussaoui** [comment]
kid3-cli should be installed on host. I can still add it here, but not sure if that will work

**Comment by loupianche** [comment]
Yes, should be added on host, Lollypop uses flatpak-spawn.

**Comment by bilelmoussaoui** [comment]
We can add it here, but it requires qt to build it. I will have to play with that later so we can ensure that the application runs perfectly fine without any packages to be installed on host.

**Comment by loupianche** [comment]
No, it's not needed.

**Comment by bilelmoussaoui** [comment]
It's not needed because you're using flatpak-spawn currently. I can patch locally and see if I can make it work. Otherwise, the user will have to install a third party package, which is not "possible" with Silverblue for example

**Comment by loupianche** [comment]
If you install kid3-cli in flatpak, nothing to patch, Lollypop will use it.

**Comment by bilelmoussaoui** [comment]
Oh that's perfect then! I will take a look and see how to include it with the minimum of dependencies :)

**Comment by loupianche** [comment]
> If you install kid3-cli in flatpak, nothing to patch, Lollypop will use it.

Was wrong :-/ Lollypop looks at flatpak-spawn...

**Comment by Eonfge** [comment]
It would perhaps be better to put Kid3 in a flatpak instead.

**Comment by rugk** [comment]
IMHO, I usually see `flatpak-spawn` used as a workaround. 
So I wonder why Lollypop prefers it here… Or actually, why do the Lollypop devs have decided to implement it like this?

Because cannot all these write/save to audio filer actions be done inside of the flatpak? Why do you need to execute it on the host?

At least, I would argue to implement a fallback algo in Lollypop, so that it uses kid3 inside of the flatpak and only falls back to flatpak-spawn if that does not work.
(Can someone maybe open an issue in the Lollypop bug tracker for this last thing? – Otherwise I'll do it.)

**Comment by loupianche** [comment]
>So I wonder why Lollypop prefers it here

Because having kid3-cli was not an option some years ago.

>At least, I would argue to implement a fallback algo in Lollypop, so that it uses kid3 inside of the 
>flatpak and only falls back to flatpak-spawn if that does not work.

Already fixed ;)

**Comment by rugk** [comment]
So this means kid3-cli can now be included in the flatpak?

**Comment by loupianche** [comment]
For 1.2.0

**Comment by felipehw** [comment]
We now have `org.kde.kid3` at Flathub.
I don't if this helps in anything ...

**Comment by rugk** [comment]
@felipehw Well... you need to ask that to the Lollypop devs. Maybe they can remove the `flatpak-spawn` workaround and thus then improve the sandbox of Lollypop?

Could we create an issue or so?

**Comment by bellegarde-c** [comment]
I can remove the flatpak-spawn :-)

**Comment by rugk** [comment]
...and it still works?

I'd still guess we should look how upstream does it/discuss it with them.

**Comment by bilelmoussaoui** [comment]
well @bellegarde-c is upstream.

You can't use the flatpak of org.kde.kid3 from the flatpak of Lollypop, you can't know it exists neither. The solution would be to bundle kid3-cli, building it requires Qt which will make the build a lot slower. Merge requests are welcome!

**Comment by Eonfge** [comment]
Closing this issue since it's put on the ToDo list for Lollypop 2:
https://gitlab.gnome.org/World/lollypop/-/issues/2711
