### ISSUE TITLE
Lollypop flatpak not recognising theme adapta

### ISSUE THREAD

**Issue by bulu009** [flathub/org.gnome.Lollypop#4]
I am on KDE Neon 5.12.5 and have kvantum theme installed in addition to adapta gtk theme and adapta flatpak theme.

But lollypop is not recognising the theme. What do I need to do?

**Comment by TingPing** [comment]
I think it is just a KDE limitation. For technical details Gtk gets information on what theme to use via XSettings on Xorg and KDE does not have a daemon for that. You can probably find, install, and configure one but that is probably a pain.

**Comment by bilelmoussaoui** [comment]
@bulu009  Do you have the same issue with  another Gtk application? If so, this is then an upstream issue.
