### ISSUE TITLE
Lollypop settings reset

### ISSUE THREAD

**Issue by Eonfge** [flathub/org.gnome.Lollypop#42]
With the migration of 3.34, [DConf access has been changed](https://github.com/flathub/org.gnome.Lollypop/pull/41/files). As such, it caused all Lollypop settings to reset.

This is something to reconsider. While it is easy to re-configure a music player, this change can be quite annoying for more complex applications. It also introduces a new issue: Using DConf 3.32, I can now no longer analyze the values in the register.

**Comment by Eonfge** [comment]
I see that about 8 hours ago, a DConf migration setting was added, but the current live build is from two hours before that. It will be advised to quickly rebuild Lollypop and to redistribute this migration flag.

**Comment by TingPing** [comment]
The build is already live.

**Comment by bilelmoussaoui** [comment]
My bad, sorry for that. Fixed that as soon as I could
