### ISSUE TITLE
Update to v1.1.99.5

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.gnome.Lollypop#45]

**Comment by Eonfge** [comment]
Plese don't. The v1.1.99 is a testrelease before the v1.2. 

When the v1.2 comes out proper, we'll have to check all updated python dependencies and we'll then also be able to update Lollypop itself.

**Comment by loupianche** [comment]
Lollypop 1.2 is out ;)

**Comment by Eonfge** [comment]
Don't forget to regenerate the python libs. Guess that some have had updates by now. Also, youtube-dl 2019.10.22 is out.
