### ISSUE TITLE
Cannot launch Easytag

### ISSUE THREAD

**Issue by ishan9299** [flathub/org.gnome.Lollypop#54]
In the menu "Modify Information" doesnt launch EasyTag

**Comment by Eonfge** [comment]
Bit late, but Lollypop only supports Kid3 directly. There is no Flatpak version of Kid3 right now, so you'll have to manually start EasyTag, or you should install Kid3 from your system's repositories

**Comment by ishan9299** [comment]
Is possible package lollypop flatpak with kid3 together?

**Comment by Eonfge** [comment]
I have looked into packaging Kid3 using Flatpak. If I'm able to do that, then that would be the preferred solution. Packaging Kid3 with Lollypop is undesirable, since they are both very distinct applications with their own use cases and technical framworks
