### ISSUE TITLE
Lollypop is not responding to dark theme variant

### ISSUE THREAD

**Issue by Javanmardi** [flathub/org.gnome.Lollypop#59]
OS: Ubuntu bionic
Kernel: 5.0.0-37-generic
DE: GNOME 3.28.4
WM Theme: Adwaita
Theme: Ambiance [GTK2/3]
Graphic driver: nvidia-driver-390.116

I recently upgraded my Lollypop from `Ubuntu PPA` to Flatpak and everything is going great (regular updating and user experience) except the Use dark theme variant from Preferences menu. This feature was doing well when I used the `PPA` version.

This is all I installed according to [this issue](https://github.com/flathub/org.gnome.Lollypop/issues/4) but still the dark theme is not working.

```
org.freedesktop.Platform.GL.nvidia-390-116
org.freedesktop.Platform.VAAPI.Intel      
org.freedesktop.Platform.openh264         
org.gnome.Lollypop                        
org.gnome.Platform                        
org.gtk.Gtk3theme.Adapta                  
org.gtk.Gtk3theme.Ambiance
org.gtk.Gtk3theme.Arc-Darker
```

![image](https://user-images.githubusercontent.com/16988499/72331485-840f1d00-36cd-11ea-9f44-e96058e429c7.png)

**Comment by bilelmoussaoui** [comment]
Because Dark themes are not a thing. You're using Ambiance, which doesn't provide a "dark theme". Not a Lollypop issue
