### ISSUE TITLE
Version not up to date

### ISSUE THREAD

**Issue by andrefmarques** [flathub/org.gnome.Lollypop#6]
At his moment the flatpak version is at 0.9.507, while the latest release is 0.9.522.

**Comment by andrefmarques** [comment]
Thank you :)

**Comment by bilelmoussaoui** [comment]
It's building correctly now https://flathub.org/builds/#/builders/2/builds/4134. Should be fixed soon!
@TingPing The test build was successful. Should have been more careful with the "distribution" build
