### ISSUE TITLE
global gnome search doesn't work for lollypop in flatpak version

### ISSUE THREAD

**Issue by aviwad** [flathub/org.gnome.Lollypop#7]
hello! Cedric told me to ask here instead of the main lollypop gitlab.
So, this is not a technical limitation because many flatpak applications can have global gnome search (example: web technical preview, files development flatpak) but lollypop doesn't show with search in gnome settings or overview in the flatpak, but it works in the normal packaged lollypop. why?

**Comment by bilelmoussaoui** [comment]
I will take a look. My app has the same problem, i will see what causes that and proivde a fix either here or upstream. Thanks for reporting

**Comment by aviwad** [comment]
awesome! thanks for looking at my report :)

**Comment by nedrichards** [comment]
I suspect you're not exporting a search provider (or if you are putting it in the correct place it doesn't have the app-id as its name).

**Comment by bilelmoussaoui** [comment]
This is an upstream issue as the dbus service must have the same name as the application ID in order to be exported
```

Exporting share/dbus-1/services/org.gnome.Lollypop.SearchProvider.service
Not exporting share/gnome-shell/search-providers/lollypop-search-provider.ini, non-allowed export filename
```
