### ISSUE TITLE
Can't connect to Libre.fm and Last.fm

### ISSUE THREAD

**Issue by felipehw** [flathub/org.gnome.Lollypop#79]
Hi,
I tested with Lollypop non-Flatpak (Ubuntu 20.04) and I successfully connected to Libre.fm and Last.fm. (Works and appears something like a **✓** at the side of the button *Connect*)
But when I tried with Flatpak of Lollypop ... it fails at connect (and doesn't appear the feedback of a **✓** at the side of the button *Connect*).

**Comment by Eonfge** [comment]
That's weird, because we're using exactly the same manifest as upstream:
https://gitlab.gnome.org/World/lollypop/-/blob/1.2.35/org.gnome.Lollypop.json

Could you try it, while running Lollypop from the console and tell me if it gives you any message?
```flatpak run org.gnome.Lollypop```

**Comment by bilelmoussaoui** [comment]
The manifest upstream is updated from time to time mostly by me. I would guess we need to update pylast maybe? 

Anyway, if you can provide some more infos, that would be helpful.

**Comment by Eonfge** [comment]
@bilelmoussaoui Then it's perhaps time to update the entire dependency list, because all packages have had some updates.

**Comment by bilelmoussaoui** [comment]
I have been planning to do so for a while :/

**Comment by Eonfge** [comment]
I made a small start, but then I went to play Civilization 6 with my sister so the second half will have to wait:
https://github.com/flathub/org.gnome.Lollypop/tree/2020.05_DepenencyUpdates

**Comment by felipehw** [comment]
@Eonfge,
the output of `flatpak run org.gnome.Lollypop` didn't produce any lines after I've clicked at *Connect*.

**Comment by Eonfge** [comment]
@felipehw 
Could you try this development version?
```
flatpak install --user https://dl.flathub.org/build-repo/19131/org.gnome.Lollypop.flatpakref
```

**Comment by felipehw** [comment]
@Eonfge 
The problem here remains ...
But this is happen just with me?

**Comment by Eonfge** [comment]
I think so. Have not heard anybody else about it, and I don't use Last FM

**Comment by felipehw** [comment]
Maybe this is a problem but just I in the "Lollypop world plus Flatpak" use "Libre FM || Last FM". 🤣🤣🤣

**Comment by Eonfge** [comment]
Well... I don't know. I must confess that it sounds bloody unlikely that you're the only person having this problem. But then again, you'll be shocked how long it sometimes takes for bugs to trickle down. I've literally had cases where I accidentally broke [Cowsay](https://flathub.org/apps/details/org.gnome.gitlab.Cowsay) without networking, and it took me months before a colleague told me.

Could you check your Flatpak permissions? perhaps you've just blocked connections to the outside world? Else, perhaps ask upstream if there might be an issue when using Libre FM and Last FM at the same time.

**Comment by felipehw** [comment]
I'm using Lollypop Flatpak with vanilla permissions (there is no file about this app at `~/.local/share/flatpak/overrides/`).
The problem exists in all variations: Just Libre.FM, just Last.FM and both at the same time.

**Comment by bilelmoussaoui** [comment]
I would probably assume an upstream bug, unless you can't with a non flatpak package

**Comment by felipehw** [comment]
This is not an upstream bug. :(
In Lollypop 1.2.35 of Ubuntu 20.04 repos, I can connect to Libre FM and Last FM without problems.
But with  Lollypop Flatpak version (1.2.35) I can't. At least in my Fedora 32 setup.

**Comment by bilelmoussaoui** [comment]
> This is not an upstream bug. :(
> In Lollypop 1.2.35 of Ubuntu 20.04 repos, I can connect to Libre FM and Last FM without problems.
> But with Lollypop Flatpak version (1.2.35) I can't. At least in my Fedora 32 setup.

what happens if you run Lollypop with `flatpak run --no-talk-name=org.freedesktop.secrets org.gnome.Lollypop`?

**Comment by felipehw** [comment]
Nothing special:
```
$ flatpak run --no-talk-name=org.freedesktop.secrets org.gnome.Lollypop
[ERROR] 2020-05-19 16:27:14 AlbumArt::get_album_artwork(): gdk-pixbuf-error-quark: Unrecognized image file format (3)
[ERROR] 2020-05-19 16:27:14 AlbumArt::get_album_artwork(): gdk-pixbuf-error-quark: Unrecognized image file format (3)
[ERROR] 2020-05-19 16:27:14 AlbumArt::get_album_artwork(): gdk-pixbuf-error-quark: Unrecognized image file format (3)
[INFO] 2020-05-19 16:27:15 Scan started
[INFO] 2020-05-19 16:27:17 Scan finished
$ 
```

**Comment by felipehw** [comment]
@bilelmoussaoui @Eonfge 
I found something!

When I run the app with this parameter: `org.gnome.Lollypop --debug`.

I get the follow message when I try connect to Libre.fm (or Last.fm):
```
[DEBUG] 2020-05-29 21:55:59 PasswordsHelper::clear(): Waiting Secret service
[DEBUG] 2020-05-29 21:55:59 PasswordsHelper::get(): Waiting Secret service
[DEBUG] 2020-05-29 21:55:59 PasswordsHelper: no items!
[DEBUG] 2020-05-29 21:55:59 LastFMBase::__on_get_password(): no attributes
```

The simple act of open the Dialog of Preferences, thrown these messages at CLI:
```
[DEBUG] 2020-05-29 21:54:31 PasswordsHelper::get(): Waiting Secret service
[DEBUG] 2020-05-29 21:54:31 PasswordsHelper::get(): Waiting Secret service
[DEBUG] 2020-05-29 21:54:31 PasswordsHelper: no items!
[DEBUG] 2020-05-29 21:54:31 PasswordsHelper: no items!
```

**Comment by Eonfge** [comment]
Could you login here and ask Cedric about it? Seems to be an upstream issue then:
https://gitlab.gnome.org/World/lollypop

**Comment by felipehw** [comment]
But at my Fedora 32. it works with the RPM version (`lollypop-1.2.35-1.fc32`).

It only fails with Flatpak ...

When I try (successfuly) to connect with Lollypop at Libre.fm in RPM version I got this messages:
```
BUG] 2020-05-30 10:10:42 PasswordsHelper::clear(): Waiting Secret service
[DEBUG] 2020-05-30 10:10:43 PasswordsHelper::get(): Waiting Secret service
```

**Comment by felipehw** [comment]
By now, I can't compare outputs because there is a new Lollypop (1.3.0) just in Flatpak.

I'll wait for the new Lollypop (version 1.3.0) arrive in Fedora RPM or Ubuntu DEB to open a issue in upstream repo about this behavior (Last.fm/Libre.fm works only at non Flatpak builds ...).

**Comment by Eonfge** [comment]
Ow sorry, I could have held off the release a bit longer if that was beneficial to your testing.

If you want to install a specific version, you can do the following:
```
flatpak update --commit 5428d62e33d46ddc2f2b9314d2706b9b2d970f5f4140338bb1b4218a19211f87 org.gnome.Lollypop
```

If you want to see all previous versions, you can always do:
```
flatpak remote-info --log flathub org.gnome.Lollypop
```

**Comment by bilelmoussaoui** [comment]
I guess this is due to xdg-desktop-portal; the keyring is sandboxed and somehow the portal might be doing something wrong?

**Comment by felipehw** [comment]
I tested the [official RPM](https://copr.fedorainfracloud.org/coprs/gnumdk/lollypop/) for Fedora. It works perfectly.

Should I open an issue in the upstream comparing the working Last.fm connect at official RPM with the behavior at Flatpak?

**Comment by felipehw** [comment]
@bilelmoussaoui 

Yes, I believe in something in this area. I'm not a developer but my "Password and Keys" (seahorse) in a environment  with RPM Lollypop shows "Passwords/Login" with entries for `org.gnome.Lollypop LASTFM` and `org.gnome.Lollypop librefm`.

The environment with Flatpak Lollypop doesn't has this entries ...

**Comment by Eonfge** [comment]
@bilelmoussaoui does that relate to `"--talk-name=org.freedesktop.secrets"`?

**Comment by bilelmoussaoui** [comment]
@felipehw Since xdg-desktop-portal  1.6.0 the apps default to a sandbox keyring (which makes sense, otherwise apps can just look at the other passwords without giving you them an explicit permission). which is now shipped by default in the latest releases of various distros. I suggest trying an other application that uses libsecret and see if you can still use it correctly. 

It might be an issue on the portal side of things but I don't think so as it's working fine in F32 with other applications I use. I suggest also looking at the logs of xdg-desktop-portal and see if you find anything interesting.

**Comment by felipehw** [comment]
@bilelmoussaoui 
How i look through the xdg-desktop-portal logs?
I tried this way:
```
$ sudo journalctl -p7 -u xdg-desktop-portal.service 
-- Logs begin at Wed 2020-04-01 14:23:42 -03, end at Sat 2020-06-06 08:38:47 -03. --
-- No entries --
```

Do you have an example of other application that uses libsecret? So I could test ...

**Comment by bilelmoussaoui** [comment]
hmm, do you mind trying Authenticator?

**Comment by felipehw** [comment]
Authenticator Flatpak succeeds in insert data to seahorse.

I'm looking here, Lollypop Flatpak also insert 1 entry (without description).

But my configured Lollypop Rpm insert 3 entries at seahorse. The normal one (without description) and 2 entries more with description: `org.gnome.Lollypop LASTFM` and `org.gnome.Lollypop librefm`.

I believe there is some problem in the action of access the keys management specifically to Last Fm and Libre Fm.

**Comment by bilelmoussaoui** [comment]
I will try to debug this and see if that's an issue on Lollypop side, it might take a while though

**Comment by felipehw** [comment]
Thanks :D

**Comment by felipehw** [comment]
Update: Someone created an issue at upstream repo: https://gitlab.gnome.org/World/lollypop/-/issues/2481

**Comment by bellegarde-c** [comment]
>Since xdg-desktop-portal 1.6.0 the apps default to a sandbox keyring (which makes sense, otherwise apps can just look at the 
>other passwords without giving you them an explicit permission).

Done some testing on up to date ArchLinux.
When lauching Lollypop with Flatpak, I see my Last.FM credentials.

So, looks it's not true and that's why it fails, Lollypop tries to read/write to non sandboxed keyring (using gi Secrets).

**Comment by bellegarde-c** [comment]
Runnin this simple python code inside Lollypop container does not add any entry to secret:

```
>>> secret = Secret.Service.get_sync(Secret.ServiceFlags.NONE, None)
>>> schema_string = "org.gnome.Lollypop: plop@plap"
>>> SecretSchema = {
...  "service": Secret.SchemaAttributeType.STRING,
...  "login": Secret.SchemaAttributeType.STRING,
... }
>>> SecretAttributes = {
...  "service": "coucou",
...  "login": "cmoi"
... }
>>> schema = Secret.Schema.new("org.gnome.Lollypop", Secret.SchemaFlags.NONE, SecretSchema)
>>> Secret.password_store_sync(schema, SecretAttributes,
...                                   Secret.COLLECTION_DEFAULT,
...                                   schema_string,
...                                   "unmot2passe")
True

```

**Comment by bilelmoussaoui** [comment]
> Runnin this simple python code inside Lollypop container does not add any entry to secret:
> 
> ```
> >>> secret = Secret.Service.get_sync(Secret.ServiceFlags.NONE, None)
> >>> schema_string = "org.gnome.Lollypop: plop@plap"
> >>> SecretSchema = {
> ...  "service": Secret.SchemaAttributeType.STRING,
> ...  "login": Secret.SchemaAttributeType.STRING,
> ... }
> >>> SecretAttributes = {
> ...  "service": "coucou",
> ...  "login": "cmoi"
> ... }
> >>> schema = Secret.Schema.new("org.gnome.Lollypop", Secret.SchemaFlags.NONE, SecretSchema)
> >>> Secret.password_store_sync(schema, SecretAttributes,
> ...                                   Secret.COLLECTION_DEFAULT,
> ...                                   schema_string,
> ...                                   "unmot2passe")
> True
> 
> ```

Which version of xdg-desktop-portal-gtk you're running? The latest releases uses a sandboxd keyring, it might have introduced some issue. How did you check if the password is saved or not?

**Comment by bellegarde-c** [comment]
xdg-desktop-portal-gtk-1.7.1-2.fc33.x86_64

I checked with secret-tool from container.

**Comment by luismglvieira** [comment]
I have this problem too, I can't use the dark theme variant and it doesn't save the last.fm credentials. Manjaro KDE. Installing from pacman or AUR gives the same results.

**Comment by bellegarde-c** [comment]
> I have this problem too, I can't use the dark theme variant and it doesn't save the last.fm credentials. Manjaro KDE. Installing from pacman or AUR gives the same results.

Not the same issue if does not work from AUR.

**Comment by bellegarde-c** [comment]
https://github.com/flathub/ch.protonmail.protonmail-bridge/issues/27 ?

**Comment by bellegarde-c** [comment]
Any news on this ?

After some more debugging:
* Lollypop is writing to sandboxed keyring
* Lollypop is reading from not sandboxed keyring

After using flatpak Lollypop, non sandboxed keyring is broken:

g-dbus-error-quark: No such secret item at path: /org/freedesktop/secrets/collection/login/777

**Comment by felipehw** [comment]
This is a sad situation.
Lollypop is the best GNOMEish Music Player and Flapak is the perfect format for a modern distribution of this kind of software.
Now, I'm using the RPM version to bypass the current Flatpak problems.

Maybe is a good idea to do mentions about these problems at the official site because it recommends Flatpak without explaining the current limitations ...

**Comment by Eonfge** [comment]
@felipehw I kind off agree with you. We should not promote applications as 'fully functional' if there are components missing compared to non-flatpak versions. For example, I discovered that the phone-integration #109 is also not fully supported. Not bad for most users I guess (I had to find it myself after all) but it does add massive 'caveat emptor' to the project.

Otherwise, I am a bit lost on this issue. I don't know enough about Lollypop or Keyring to reasonably assist in this issue. In the end, I just roll the python updates.

**Comment by felipehw** [comment]
@eonfge

I feel your pain. I help to keep a Flatpak here (Zotero) but I'm not a technical person so I can't fix non trivial problems.

**Comment by bellegarde-c** [comment]
No idea for this issue but will give a look for the phone integration ;)

**Comment by Eonfge** [comment]
@bellegarde-c Ow, I think I totally forgot to tell you. My apology, the memo must have slipped through, what with all the other things going on. Same for the no-host migration, it doesn't have the highest priority and I rather do it when we all have the time to do it properly.

**Comment by bellegarde-c** [comment]
![Capture d’écran du 2021-01-05 14-39-21](https://user-images.githubusercontent.com/57196916/103700216-73257e80-4fa4-11eb-94cc-1f4a9a088efb.png)


Fixed but found another issue.

https://github.com/flatpak/xdg-desktop-portal/issues/557
