### ISSUE TITLE
Lollypop Open-With feature broken: Gio.AppInfo.get_all_for_type() always return []

### ISSUE THREAD

**Issue by bellegarde-c** [flathub/org.gnome.Lollypop#99]
Lollypop needs this to get applications handling music files.

It then launch the app with flatpak-spawn.

**Comment by Eonfge** [comment]
Uhm. I'm not following you. Are you saying that the flatpak permissions are wrong?

**Comment by bellegarde-c** [comment]
I have no idea what is wrong, it may be an issue in flatpak... (missing portal ?)

**Comment by bellegarde-c** [comment]
Maybe a fix here: https://github.com/flathub/com.github.donadigo.appeditor/issues/6

**Comment by bilelmoussaoui** [comment]
Apps can't access the installed apps by default. The thing done in appeditor is a huge hack that shouldn't be used in a music player iirc. Is it used to figure out if an audio tagging app is installed?

**Comment by bellegarde-c** [comment]
Yes, it's used to get applications associated with mime type.

![Capture_d_écran_du_2020-09-14_13-34-46](https://user-images.githubusercontent.com/57196916/93172021-61387b00-f72a-11ea-8289-71356ae13c1d.png)

**Comment by bilelmoussaoui** [comment]
Any reason for not using Gio.AppInfo.launch_default_for_uri ? this should call the OpenURI portal for you and present a similar dialog to what you have got in your screenshot

**Comment by bellegarde-c** [comment]
Yes, the dialog was added to let user choosing what application to launch: file manager, tag editor, ...

**Comment by bilelmoussaoui** [comment]
Using `Gio.AppInfo.launch_default_for_uri` would be the proper way to do it then :)

**Comment by bellegarde-c** [comment]
**Let the user choosing** :p

**Comment by bellegarde-c** [comment]
https://gitlab.gnome.org/World/lollypop/-/issues/287

**Comment by bilelmoussaoui** [comment]
Ah right, because the Gio implementation decides of a default one after using it three times. You can call the portal manually then https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-method-org-freedesktop-portal-OpenURI.OpenURI where you can always ask the user to select an application.

**Comment by bellegarde-c** [comment]
`gdbus call -e -d org.freedesktop.portal.Desktop -o /org/freedesktop/portal/desktop -m org.freedesktop.portal.OpenURI.OpenURI "" file:///etc/fstab {}`

This does nothing here, am I missing something ?

**Comment by bilelmoussaoui** [comment]
You should handle the request part. The call returns a object path to the request made to the portal and wait for a response signal once the user accepts the interaction (choose an app) or closed it /an error happened

**Comment by bellegarde-c** [comment]
```
from gi.repository import Gio, GLib

def on_signal(*ignore):
    print("plop")

bus = Gio.bus_get_sync(Gio.BusType.SESSION, None)
result=bus.call_sync("org.freedesktop.portal.Desktop", "/org/freedesktop/portal/desktop", "org.freedesktop.portal.OpenURI", "OpenURI", GLib.Variant.new_tuple(GLib.Variant.new_string(""), GLib.Variant.new_string("file:///etc"), GLib.Variant("a{sv}", {})), None, Gio.DBusCallFlags.NONE, -1, None)
request_handle = result.unpack()[0]
bus.signal_subscribe("org.freedesktop.portal.Desktop",
                     "org.freedesktop.portal.Request",
                     "Response",
                     request_handle,
                     None,
                     Gio.DBusSignalFlags.NO_MATCH_RULE,
                     on_signal)
loop = GLib.MainLoop()
loop.run()
```

Here it does not work :-/

**Comment by bilelmoussaoui** [comment]
I will try it later today, does busctl/bustle reports anything?

**Comment by bellegarde-c** [comment]
XDP: Not handling file uri file:///etc
XDP: Not handling file uri file:///etc/fstab

**Comment by bilelmoussaoui** [comment]
@bellegarde-c from the specs ` Note that file:// uris are explicitly not supported by this method. To request opening local files, use OpenFile().`

**Comment by bellegarde-c** [comment]
@bilelmoussaoui Do you have a solution to get file handle on an URI ?

**Comment by bilelmoussaoui** [comment]
I'm not sure why you would need to explicitly use the file URI here? you can just open the file & pass the fd to OpenFile instead?

**Comment by bellegarde-c** [comment]
Because the file may be sftp://

**Comment by Eonfge** [comment]
Closing this issue since it's put on the ToDo list for Lollypop 2:
https://gitlab.gnome.org/World/lollypop/-/issues/2711
